apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: vramana98/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4005
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://auth-service-db:5432/auth
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: JWT_SECRET
              value: a093c919d3d5af4aee1511e29ea3cd1a0734716eb5421157ac2e245f292dd3d2
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  selector:
    app: auth-service
  ports:
    - port: 4005
      targetPort: 4005
  type: ClusterIP
