version: "3.8"

services:
  patient-service-db:
    image: postgres:latest  # ✅ Use official image
    container_name: patient-service-db
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/patient-service-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_SQL_INIT_MODE: always
    depends_on:
      patient-service-db:
        condition: service_healthy
    networks:
      - internal

  billing-service:
    build:
      context: ../billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

networks:
  internal:
    driver: bridge